### ISSUE TITLE
ENET2  1-wire server

### ISSUE THREAD

**Issue by wrmo** [metbosch/homebridge-http-temperature#13]
I have an eds enet2 1-wire server (up to 21 1-wire devices). It does not put out json.
But I can poll individual devices with:

http://192.168.178.75/gettag.csv?romid=160008025B548B10&tag=Temperature&title=0

the output is just the temperature value in celsius eg.:
15.3

Line 66 can not return just the body text, as this.fieldname is never empty. (default: " temperature")

Can you change line 26?
  this.fieldName = config["field_name"] || "";

**Comment by metbosch** [comment]
Hi @wrmo ,

Now it should work, the issue was reported some weeks in #11 . Just set `field_name: ""` in your config.json.

**Comment by metbosch** [comment]
@wrmo ,
Is it working?

**Comment by wrmo** [comment]
Yes, it works great. Thank you very much. Right now I have 4 1-wire extension, will extent them to tank water heater and solar air and water panels.
The endet works reliable, also after power failures.
Wolfgang
