### ISSUE TITLE
complex data structure

### ISSUE THREAD

**Issue by cpo81** [metbosch/homebridge-http-temperature#21]
Hi, I get a response in the form

{ "Header":{ "Version":5, "Device":"80", "Timestamp":1588082165 }, "Data":{ "Inputs":[ { "Number":4, "AD":"A", "Value":{ "Value":15.7, "Unit":"1" } } ]}, "Status":"OK", "Status code":0 }

from the http request from my device.
How can I get the Value 15.7?
I tried [0].[0].Value and some similar things.
Can you help me?

**Comment by MatsA** [comment]
Hi! Havn't tested but think `Data.Inputs[0].Value.Value` will do the job.

**Comment by metbosch** [comment]
@cpo81 You should set the `field_name` to what @MatsA said.
Could you please let us know if it works?

**Comment by metbosch** [comment]
Closing the issue as it is already supported
