### ISSUE TITLE
Default max_temp does not handle southern summers!

### ISSUE THREAD

**Issue by jlg89** [metbosch/homebridge-http-temperature#23]
If you're using Celsius, none of this applies. If you're using Fahrenheit, the default min_temp is good for pretty much everyplace on earth except Antarctica. The default max_temp, though, doesn't cut it if you're within the 38th parallels. It's not a critical issue, but the max_temp default should probably be something like 120 or 130.

**Comment by metbosch** [comment]
I put the values thinking on extreme Celsius values. I will try to increase the value in the following releases. Thanks for the insight.

**Comment by metbosch** [comment]
Fixed in release 0.8.1

**Comment by metbosch** [comment]
Commit: https://github.com/metbosch/homebridge-http-temperature/commit/b99b6547e98513c14697581229d8d9b7b52677c1
