### ISSUE TITLE
Question: how to display temperature with decimal point in Home app?

### ISSUE THREAD

**Issue by dkossman** [metbosch/homebridge-http-temperature#24]
my endpoint returns the temperature in celcius with 2 decimal points of precision (e.g. 28.25).  However the temperature displayed on the Home app is rounded to the nearest degree F.  In the Eve app, the temperature is shown with one decimal place.  Am I doing something wrong?  Is there a way to have the Home app display at least one decimal place?

config.json:
```
{
        "accessory": "HttpTemperature",
        "name": "Pool Temperature",
        "update_interval": "0",
        "field_name": "",
        "url": "http://10.0.1.18/temp.php?sensor=Pool&scale=C"
    },
```

**Comment by metbosch** [comment]
The plugin does nothing about decimation. This is something related to the home app and how the data is displayed there. I searched a bit about it and seems home app is rounding to 0.5 values
