### ISSUE TITLE
Support for negative values

### ISSUE THREAD

**Issue by MichaelS75** [metbosch/homebridge-http-temperature#3]
First of all, thank you for this great plugin.
Today I discovered that only 0 or positive temperature values are supported.

To fix the issue and support negative temperatures too, replace the following code in
index.js (line 74-76)
```
      this.temperatureService
         .getCharacteristic(Characteristic.CurrentTemperature)
         .on('get', this.getState.bind(this))
```
by
```
      this.temperatureService
         .getCharacteristic(Characteristic.CurrentTemperature)
         .on('get', this.getState.bind(this))
         .setProps({
             minValue: -50,
             maxValue: 100
         });
```
and you're done.
Cheers, MichaelS75

**Comment by metbosch** [comment]
Hi,
Thanks for the point!
I fixed it and updated the new code on the npm (version 0.0.3).
