### ISSUE TITLE
Temperature works but no Humidity value

### ISSUE THREAD

**Issue by mploetner** [metbosch/homebridge-http-temperature#31]
I tried both http plugins (temp and humidity) from you but only with temp plugin I get values. Humidity always shows 0 whole the json file offers a value. Below my config code. Is there something wrong. Sorry I'm new to this

**Comment by mploetner** [comment]
Sorry here the code

{
            "accessory": "HttpHumidity",
            "name": "Outside Humidity",
            "url": "http://192.168.1.128/status?type=json",
            "http_method": "GET",
            "field_name": "ext_humidity.0.hum"
        },
        {
            "accessory": "HttpTemperature",
            "name": "Temperatur Van",
            "url": "http://192.168.1.128/status?type=json",
            "http_method": "GET",
            "field_name": "ext_temperature.0.tC"
        }

**Comment by metbosch** [comment]
@mploetner Could you post what is returning the `http://192.168.1.128/status?type=json` url?

**Comment by metbosch** [comment]
Closing since there is no answer from the requestor
