### ISSUE TITLE
Humidity does'nt work

### ISSUE THREAD

**Issue by Cavas17** [metbosch/homebridge-http-temperature#34]
Hello,

Like the issue thread #31, humidity always show 0.

In Homebridge UI I see this warning message :
`This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "Error: Invalid value received" (object). See https://homebridge.io/w/JtMGR for more info.`

However my URL return 58 at this time.

Here is my JSON :

```
{
    "accessory": "HttpHumidity",
    "name": "Humidite cabinet",
    "url": "http://10.0.1.103/core/api/jeeApi.php?apikey=4pyz8UFyJrbQUiGqQbj0u6ACJGtX6J2C&type=cmd&id=3624",
    "field_name": "",
    "_bridge": {
      "username": "0E:83:DD:29:58:C9",
      "port": 55198
     }
 }
```

Any idea ?
Thanks

**Comment by metbosch** [comment]
If *field_name* is empty the plugin returns the plain data from endpoint after checking that its a number.
@Cavas17 Can you run the test with `"debug": true` option and provide the debug logs to check the values that plugin receives?

**Comment by metbosch** [comment]
Closing due to lack of response
