### ISSUE TITLE
shelly 1PM with a temperature add-on

### ISSUE THREAD

**Issue by colussim** [metbosch/homebridge-http-temperature#35]
Hello,
I would like to use this plugin with a shelly 1PM with a temperature add-on.
I use this configuration :
{
    "accessory": "HttpTemperature",
    "name": "Temperature Exterieur",
    "url": "http://X.X.X.X/rpc/Temperature.GetStatus?id=100&format=json",
    "http_method": "GET",
    "field_name": "tC",
    "units": "C",
    "debug": true,
    "auth": {
        "user": "admin",
        "pass": "XXXXXXXX"
    }
}

the shelly query returns the following result:
{"id": 100,"tC":17.8, "tF":64.1}

I have the following error : Error updating state: Unexpected end of JSON input

An idea of the problem ?

Thanks,
Emmanuel

**Comment by metbosch** [comment]
@colussim Please check that there is no hidden character after the JSON.
The error seems to comes from the JSON parser which is not able to properly parse the data.

**Comment by colussim** [comment]
Hi @metbosch  sorry for the late return, it was indeed a character problem in the json file, Thanks
